name: Deploy to Firebase Hosting on merge or pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  build_and_deploy:
    name: Prod Backend - Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          touch .env
          echo API_KEY: '${{ secrets.API_KEY }}' >> .env
          echo PROJECTURL: '${{ secrets.PROJECTURL }}' >> .env
          cat .env

      - name: 'Install Dependencies & Build'
        run: npm ci && npm run build
      
      - name: 'Deploy to firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRIANGLE_WEBSITE_DEV }}'
          channelId: live
          projectId: triangle-website-dev
          target: api-vpitriangle
